CREATE TABLE IF NOT EXISTS preguntes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pregunta TEXT NOT NULL,
  imatge VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS respostes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pregunta_id INT NOT NULL,
  resposta TEXT NOT NULL,
  es_correcta TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_respostes_pregunta FOREIGN KEY (pregunta_id)
    REFERENCES preguntes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
